#!/usr/bin/env python3
"""Generates Keymap table (Kotlin) from the hardware firmware's keymap.h.

Usage: gen_keymap.py <path/to/firmware/keymap.h> <output Keymap.kt>
"""
import re
import sys

src = open(sys.argv[1], encoding="utf-8").read()

defines = {m.group(1): int(m.group(2), 16)
           for m in re.finditer(r"#define\s+(KEY_\w+)\s+(0x[0-9a-fA-F]+)", src)}

labels = []
for m in re.finditer(r"^// Byte\s+(\d+):\s+(.*)$", src, re.M):
    labels.extend(m.group(2).split())
assert len(labels) == 120, len(labels)

entries = re.findall(r"\{(KEY_\w+),\s*(true|false)\}", src)
assert len(entries) == 120, len(entries)

def kt(label):
    return label.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


lines = []
for (name, shift), label in zip(entries, labels):
    lines.append('    KeyDef("%s", 0x%02x, %s),  // %s' % (kt(label), defines[name], shift, name))

out = """// GENERATED by tools/gen_keymap.py from firmware/keymap.h. Do not edit by hand.
package jp.up_frontier.mozc.conveyorbelt.keyboard

/** 120 entries in shift-register read order (byte 0..14, MSB..LSB). */
val KEYMAP: List<KeyDef> = listOf(
%s
)
""" % "\n".join(lines)
open(sys.argv[2], "w", encoding="utf-8").write(out)
print("wrote", sys.argv[2])
